baseURL = 'https://sleepwal.github.io/'
title = 'SleepWalker Blog'
theme = ['github.com/Sleepwal/hugo-theme-editorial']
# theme = 'hugo-theme-editorial'  # 使用本地 themes/ 目录
languageCode = 'zh-CN'

[params]
  author = "SleepWalker"
  description = "博客"
  mainSections = ["post"]
  enableDarkMode = true

[params.article]
  toc = true
  readingTime = true

[params.font]
  google = true

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[menu]
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2
[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 3
[[menu.main]]
  identifier = "categories"
  name = "分类"
  url = "/categories/"
  weight = 4
